# Site settings
title: Predicting Healthcare Cost
subtitle: A BIO 260 and CSCI E107 Project
url: /DataScienceFinalProject
description: "A BIO 260 and CSCI E107 Project"
title_two: "Among Medicare Beneficiaries in Massachusetts"
meta_author: Xiner Zhou Paula Jacobs Shirley Galbiati

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  related: Related Articles
  credits: Credits

# Related Links
related: 
  - line: ' Algorithmic Prediction of Health-Care Costs'
    url: http://people.csail.mit.edu/gjw/papers/healthcare.pdf
  - line: ' Predicting Costs Among Medicare beneficiaries With Heart Failure'
    url: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3288564/
  - line: ' Using Diagnoses to Describe Populations and Predict Costs'
    url: http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4194673/

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>. This Jekyll implementation can be found at <a href="https://github.com/jeromelachaud/freelancer-theme"> this github page.</a> Stockphotos are free from <a href="https://www.pexels.com/">Pexels</a> and <a href="http://barnimages.com/">barnimages</a>. Icons from Font <a href="http://fortawesome.github.io/Font-Awesome/3.2.1/icons/">Font Awesome</a>'

# Build settings
markdown: kramdown
permalink: pretty
